"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _store_card from './store-card.bones.json'
import _hospital_card from './hospital-card.bones.json'

registerBones({
  "store-card": _store_card,
  "hospital-card": _hospital_card,
})
