spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jakarta:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
        generate_statistics: false

logging:
  level:
    root: INFO
    com.upchaar_aayog: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: WARN

server:
  port: 8080
  shutdown: graceful
